language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - echo 'extension = "zmq.so"' > /tmp/zmq.ini && phpenv config-add /tmp/zmq.ini;
  - composer selfupdate
  - composer install --dev

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpcs --standard=./phpcs.xml -n --report=gitblame ./src
  - if [ $(phpenv version-name) = '5.5' ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
  - vendor/bin/bugfree lint src/

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

notifications:
  webhooks:
    urls:
      - http://satisio.us/repositories/buildhook/
    on_success: always
    on_failure: always
    on_start: true
